name = "QuantumOpticsControlExtensions"
uuid = "39814406-9e3b-4058-9bdd-9f026a4553e9"
authors = ["Michael Goerz <mail@michaelgoerz.net> and contributors"]
version = "0.0.1"

[deps]
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"

[compat]
julia = "1.6"
QuantumOptics = "^1"
