name = "QuantumOpticsControlExtensions"
uuid = "39814406-9e3b-4058-9bdd-9f026a4553e9"
authors = ["Michael Goerz <mail@michaelgoerz.net> and contributors"]
version = "0.0.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
